#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Plot heatmaps for the extracted surface d-orbital Hamiltonian.

Input is the .npz file generated by extract_openmx_hamiltonian.py. By default
the script writes PNG files to the same directory as the input matrix:

  hamiltonian_d_surface_spin0_expanded.png
  hamiltonian_d_surface_spin0_block_norm.png

For spin-polarized calculations, one pair of figures is written per spin
channel.
"""

import argparse
from pathlib import Path

import numpy as np


def load_matrix(path):
    data = np.load(path, allow_pickle=False)
    if "H_d" not in data:
        raise SystemExit(f"[error] Missing H_d array in {path}")
    h = data["H_d"]
    if h.ndim != 5:
        raise SystemExit(f"[error] Expected H_d with 5 dimensions, got shape {h.shape}")

    atom_ids = (
        data["surface_atom_ids"].astype(str)
        if "surface_atom_ids" in data else
        np.array([f"A{i + 1}" for i in range(h.shape[1])], dtype="<U32")
    )
    d_labels = (
        data["d_labels"].astype(str)
        if "d_labels" in data else
        np.array([[f"d{j + 1}" for j in range(h.shape[3])]
                  for _ in range(h.shape[1])], dtype="<U32")
    )
    return h, atom_ids, d_labels


def expanded_matrix(h_spin):
    n_atoms, _, n_di, n_dj = h_spin.shape
    if n_di != n_dj:
        raise SystemExit(
            f"[error] Expected square d blocks, got ({n_di}, {n_dj})"
        )
    out = np.full((n_atoms * n_di, n_atoms * n_di), np.nan, dtype=np.float64)
    for i in range(n_atoms):
        for j in range(n_atoms):
            r0 = i * n_di
            c0 = j * n_di
            out[r0:r0 + n_di, c0:c0 + n_di] = h_spin[i, j]
    return out


def block_norm_matrix(h_spin):
    return np.linalg.norm(np.nan_to_num(h_spin, nan=0.0), axis=(2, 3))


def symmetric_abs_limit(matrix, percentile):
    finite = matrix[np.isfinite(matrix)]
    if finite.size == 0:
        return 1.0
    limit = float(np.percentile(np.abs(finite), percentile))
    return limit if limit > 0 else float(np.max(np.abs(finite)) or 1.0)


def add_atom_grid_lines(ax, n_atoms, n_d):
    for idx in range(1, n_atoms):
        pos = idx * n_d - 0.5
        ax.axhline(pos, color="black", linewidth=0.25, alpha=0.35)
        ax.axvline(pos, color="black", linewidth=0.25, alpha=0.35)


def plot_expanded(matrix, atom_ids, n_d, output, cmap, percentile, dpi):
    import matplotlib.pyplot as plt

    n_atoms = len(atom_ids)
    limit = symmetric_abs_limit(matrix, percentile)

    fig_size = max(7.0, min(18.0, 0.18 * matrix.shape[0]))
    fig, ax = plt.subplots(figsize=(fig_size, fig_size), constrained_layout=True)
    im = ax.imshow(
        matrix,
        origin="lower",
        cmap=cmap,
        vmin=-limit,
        vmax=limit,
        interpolation="nearest",
        aspect="equal",
    )
    add_atom_grid_lines(ax, n_atoms, n_d)

    centers = np.arange(n_atoms) * n_d + (n_d - 1) / 2.0
    if n_atoms <= 40:
        ax.set_xticks(centers)
        ax.set_yticks(centers)
        ax.set_xticklabels(atom_ids, rotation=90, fontsize=6)
        ax.set_yticklabels(atom_ids, fontsize=6)
    else:
        ax.set_xticks([])
        ax.set_yticks([])

    ax.set_title("Surface d-orbital Hamiltonian")
    ax.set_xlabel("surface atom / d orbital")
    ax.set_ylabel("surface atom / d orbital")
    cbar = fig.colorbar(im, ax=ax, shrink=0.82)
    cbar.set_label("Hamiltonian matrix element")
    fig.savefig(output, dpi=dpi)
    plt.close(fig)


def plot_block_norm(matrix, atom_ids, output, cmap, dpi):
    import matplotlib.pyplot as plt

    n_atoms = len(atom_ids)
    fig_size = max(6.0, min(14.0, 0.32 * n_atoms))
    fig, ax = plt.subplots(figsize=(fig_size, fig_size), constrained_layout=True)
    im = ax.imshow(
        matrix,
        origin="lower",
        cmap=cmap,
        interpolation="nearest",
        aspect="equal",
    )
    if n_atoms <= 60:
        ticks = np.arange(n_atoms)
        ax.set_xticks(ticks)
        ax.set_yticks(ticks)
        ax.set_xticklabels(atom_ids, rotation=90, fontsize=6)
        ax.set_yticklabels(atom_ids, fontsize=6)
    else:
        ax.set_xticks([])
        ax.set_yticks([])

    ax.set_title("Surface atom-pair d-block norm")
    ax.set_xlabel("surface atom")
    ax.set_ylabel("surface atom")
    cbar = fig.colorbar(im, ax=ax, shrink=0.82)
    cbar.set_label("Frobenius norm of d-d block")
    fig.savefig(output, dpi=dpi)
    plt.close(fig)


def parse_spin_selection(text, nspin):
    if text.lower() == "all":
        return list(range(nspin))
    out = []
    for part in text.split(","):
        part = part.strip()
        if not part:
            continue
        idx = int(part)
        if idx < 0 or idx >= nspin:
            raise SystemExit(f"[error] Spin index {idx} out of range 0..{nspin - 1}")
        out.append(idx)
    if not out:
        raise SystemExit("[error] Empty --spin selection")
    return out


def main(argv=None):
    p = argparse.ArgumentParser(
        description="Plot heatmaps from hamiltonian_d_surface.npz.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("input", help="Input .npz from extract_openmx_hamiltonian.py.")
    p.add_argument(
        "--mode", choices=["expanded", "block-norm", "both"], default="both",
        help="expanded: full d-orbital matrix; block-norm: atom-pair block norm.",
    )
    p.add_argument(
        "--spin", default="all",
        help="Spin channel to plot: all, 0, 1, or comma list such as 0,1.",
    )
    p.add_argument(
        "--cmap", default="RdBu_r",
        help="Matplotlib colormap for the expanded signed matrix.",
    )
    p.add_argument(
        "--norm-cmap", default="viridis",
        help="Matplotlib colormap for the non-negative block-norm matrix.",
    )
    p.add_argument(
        "--percentile", type=float, default=99.0,
        help="Symmetric color limit percentile for expanded heatmaps.",
    )
    p.add_argument("--dpi", type=int, default=300, help="Output PNG resolution.")
    args = p.parse_args(argv)

    input_path = Path(args.input)
    if not input_path.is_file():
        raise SystemExit(f"[error] Matrix file not found: {input_path}")

    h, atom_ids, _ = load_matrix(input_path)
    spins = parse_spin_selection(args.spin, h.shape[0])
    out_dir = input_path.parent
    stem = input_path.stem

    for spin in spins:
        h_spin = h[spin]
        n_d = h_spin.shape[2]
        if args.mode in ("expanded", "both"):
            mat = expanded_matrix(h_spin)
            out = out_dir / f"{stem}_spin{spin}_expanded.png"
            plot_expanded(mat, atom_ids, n_d, out, args.cmap, args.percentile, args.dpi)
            print(f"[done] Wrote {out}")

        if args.mode in ("block-norm", "both"):
            mat = block_norm_matrix(h_spin)
            out = out_dir / f"{stem}_spin{spin}_block_norm.png"
            plot_block_norm(mat, atom_ids, out, args.norm_cmap, args.dpi)
            print(f"[done] Wrote {out}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
